//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day33
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizzas
    {
        public int PizzaId { get; set; }
        public string PizzaName { get; set; }
        public string Price { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
    }
}
