//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day31
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int customerid { get; set; }
        public string customername { get; set; }
        public Nullable<System.DateTime> lastorderdate { get; set; }
    }
}
