//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day31
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PracticeDBEntities : DbContext
    {
        public PracticeDBEntities()
            : base("name=PracticeDBEntities")
        {
            Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Department1> Departments1 { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee1> Employees1 { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<one> one { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<tableA> tableAs { get; set; }
        public virtual DbSet<tableB> tableBs { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<two> twoes { get; set; }
        public virtual DbSet<testing> testings { get; set; }
        public virtual DbSet<v> v { get; set; }
        public virtual DbSet<v1> v1 { get; set; }
        public virtual DbSet<v2> v2 { get; set; }
        public virtual DbSet<v4> v4 { get; set; }
        public virtual DbSet<view_task3> view_task3 { get; set; }
        public virtual DbSet<view_task4> view_task4 { get; set; }
    
        [DbFunction("PracticeDBEntities", "fn_getStudents")]
        public virtual IQueryable<fn_getStudents_Result> fn_getStudents(string a)
        {
            var aParameter = a != null ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_getStudents_Result>("[PracticeDBEntities].[fn_getStudents](@a)", aParameter);
        }
    
        [DbFunction("PracticeDBEntities", "getlastnyear")]
        public virtual IQueryable<getlastnyear_Result> getlastnyear(Nullable<int> n)
        {
            var nParameter = n.HasValue ?
                new ObjectParameter("n", n) :
                new ObjectParameter("n", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getlastnyear_Result>("[PracticeDBEntities].[getlastnyear](@n)", nParameter);
        }
    
        [DbFunction("PracticeDBEntities", "test")]
        public virtual IQueryable<test_Result> test()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<test_Result>("[PracticeDBEntities].[test]()");
        }
    
        public virtual int Addproc(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Addproc", aParameter, bParameter);
        }
    
        public virtual int Addproc1(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Addproc1", aParameter, bParameter);
        }
    
        public virtual int Addproc2(Nullable<int> a, Nullable<int> b, ObjectParameter c, ObjectParameter d)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Addproc2", aParameter, bParameter, c, d);
        }
    
        public virtual int CheckStock(string productName)
        {
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CheckStock", productNameParameter);
        }
    
        public virtual int displaydata(string tbl)
        {
            var tblParameter = tbl != null ?
                new ObjectParameter("tbl", tbl) :
                new ObjectParameter("tbl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("displaydata", tblParameter);
        }
    
        public virtual int divide(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("divide", aParameter, bParameter);
        }
    
        public virtual int GetByCustId(Nullable<int> custId, ObjectParameter qty, ObjectParameter product)
        {
            var custIdParameter = custId.HasValue ?
                new ObjectParameter("CustId", custId) :
                new ObjectParameter("CustId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetByCustId", custIdParameter, qty, product);
        }
    
        public virtual int getdata(Nullable<int> age)
        {
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getdata", ageParameter);
        }
    
        public virtual int GetOrders_ByDate(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetOrders_ByDate", startDateParameter, endDateParameter);
        }
    
        public virtual int GetRow(Nullable<int> startRow, Nullable<int> endRow)
        {
            var startRowParameter = startRow.HasValue ?
                new ObjectParameter("StartRow", startRow) :
                new ObjectParameter("StartRow", typeof(int));
    
            var endRowParameter = endRow.HasValue ?
                new ObjectParameter("EndRow", endRow) :
                new ObjectParameter("EndRow", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetRow", startRowParameter, endRowParameter);
        }
    
        public virtual ObjectResult<getstudents_Result> getstudents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getstudents_Result>("getstudents");
        }
    
        public virtual int InsertStudent(Nullable<int> studentId, string name, Nullable<int> age, string grade)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var gradeParameter = grade != null ?
                new ObjectParameter("Grade", grade) :
                new ObjectParameter("Grade", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStudent", studentIdParameter, nameParameter, ageParameter, gradeParameter);
        }
    
        public virtual int myproc(Nullable<int> id, string cname, Nullable<int> ag, string grad)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var cnameParameter = cname != null ?
                new ObjectParameter("cname", cname) :
                new ObjectParameter("cname", typeof(string));
    
            var agParameter = ag.HasValue ?
                new ObjectParameter("ag", ag) :
                new ObjectParameter("ag", typeof(int));
    
            var gradParameter = grad != null ?
                new ObjectParameter("grad", grad) :
                new ObjectParameter("grad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("myproc", idParameter, cnameParameter, agParameter, gradParameter);
        }
    
        public virtual ObjectResult<sp_getemp_Result> sp_getemp(Nullable<int> d, Nullable<int> sal)
        {
            var dParameter = d.HasValue ?
                new ObjectParameter("d", d) :
                new ObjectParameter("d", typeof(int));
    
            var salParameter = sal.HasValue ?
                new ObjectParameter("sal", sal) :
                new ObjectParameter("sal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getemp_Result>("sp_getemp", dParameter, salParameter);
        }
    
        public virtual ObjectResult<sp_getEmpByJoin_Result> sp_getEmpByJoin(Nullable<System.DateTime> d1, Nullable<System.DateTime> d2)
        {
            var d1Parameter = d1.HasValue ?
                new ObjectParameter("d1", d1) :
                new ObjectParameter("d1", typeof(System.DateTime));
    
            var d2Parameter = d2.HasValue ?
                new ObjectParameter("d2", d2) :
                new ObjectParameter("d2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getEmpByJoin_Result>("sp_getEmpByJoin", d1Parameter, d2Parameter);
        }
    
        public virtual int spCheckBooksStock()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCheckBooksStock");
        }
    
        public virtual int spGetProductsByCategory(string cName)
        {
            var cNameParameter = cName != null ?
                new ObjectParameter("CName", cName) :
                new ObjectParameter("CName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetProductsByCategory", cNameParameter);
        }
    }
}
