//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day31
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string Region { get; set; }
        public Nullable<decimal> SaleAmount { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
    }
}
