//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day31
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_task4
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public Nullable<decimal> TotalSales { get; set; }
        public Nullable<long> SalesRank { get; set; }
    }
}
